# -*- coding: utf-8 -*-
"""Snippets: Importing libraries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/snippets/importing_libraries.ipynb

# New section
"""

import numpy as np

def get_bit(bit_array, n):
    """Checks if n-th bit is set (composite)."""
    return (bit_array[n // 8] >> (n % 8)) & 1

def set_bit(bit_array, n):
    """Sets the n-th bit (marks as composite)."""
    bit_array[n // 8] |= (1 << (n % 8))